#!/usr/bin/env python3 #-m cProfile -s tottime

#
# Finds an equation given a target number by iterating through all possible
# equations and returning close approximations.
#

import math # https://docs.python.org/3/library/math.html
import sys

from equation import generate, stringify
import number

if __name__ == '__main__':
    max_size = 9

    target = number.create(sys.argv[1]) if len(sys.argv) > 1 else number.create('1.61803398874989484820458683436563') # golden ratio
    min_diff = (10 ** -number.create(sys.argv[2])) if len(sys.argv) > 2 else number.create(1e-12)

    total_count = 0
    last_count = 1
    est_count = 1
    for size in range(1, max_size + 1):
        current_count = 0
        for eq, sim in generate(size):
            value = sim[0]
            current_count += 1
            if abs(value - target) < min_diff:
                digits = round(-math.log10(abs(value - target)), 1) if value != target else 16
                print(f'\r{stringify(eq)} = {value} (digits: {digits})')
            if current_count % 1000000 == 0:
                print(f'\riterations: {(total_count + current_count) / 1e6:.0f}M size: {size} progress: {100 * current_count / est_count:.2f}% ', end='', file=sys.stderr)
        total_count += current_count
        est_count = current_count * current_count / last_count
        last_count = current_count
